### ISSUE TITLE
findSpyServerClient is inconsistent with SoapySpyServerClient

### ISSUE THREAD

**Issue by righthalfplane** [pothosware/SoapySpyServer#6]
findSpyServerClient is inconsistent with SoapySpyServerClient

I had to add -

       result["host"] = args.at("host");
       result["port"] = args.at("port");

to the SoapySDR::Kwargs in findSpyServerClient because SoapySpyServerClient expected to find them in the SoapySDR::Kwargs created by findSpyServerClient.

**Comment by ncorgan** [comment]
Fixed, thanks!
